version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-api-container
    image: user-api-image
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
